HomeApp/urls.py
from django.urls import path, include
from . import views

app_name = 'HomeApp'


urlpatterns = [
    path('', views.HomeView, name="ViewHome"),
    path('create_post/', views.CreatePostView, name="ViewCreatePost"),
    path('view_post/', views.ViewPostView, name="ViewPostView"),
    path('reply_post/<int:post_id>/', views.ViewPostDetail, name="ViewPostDetail"),
    path('edit_post/<int:post_id>/', views.ViewEditPost, name="ViewEditPost"),
    path('view_changes/<int:post_id>/', views.ViewChangesVersion, name="ViewChangesVersion"),
    path('rate_user/<int:user_id>/', views.ViewRateUser, name="ViewRateUser"),
    path('view_profile/<int:user_id>/', views.ViewUserProfile, name="ViewProfile"),
    path('delete_post/<int:post_id>', views.ViewDeletePost, name="ViewDeletePost")



]

sprache/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("HomeApp.urls")),
    path('account/', include("AccountApp.urls")),
]

HomeApp/models.py
from ckeditor.fields import RichTextField
from django.db import models

from django.utils import timezone
from AccountApp.models import WebUser

class Post(models.Model):
    POST_TYPES = [
        ('movie_quote', 'Movie Quote'),
        ('book_quote', 'Book Quote'),
        ('cafe_sign', 'Cafe Sign'),
        ('other', 'Other'),
    ]

    user = models.ForeignKey(WebUser, on_delete=models.CASCADE)
    content = RichTextField()
    type_of_post = models.CharField(max_length=20, choices=POST_TYPES, default='other')
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        time_str = self.created_at.strftime("%I:%M %p on %d-%m-%Y")
        return f"{self.user.username} posted a {self.get_type_of_post_display()} at {time_str}"

class OriginalPostContent(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    content = RichTextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Original content of {self.post} created at {self.created_at}"

class Comment(models.Model):
    user = models.ForeignKey(WebUser, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    content = RichTextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.post}"

class PostVersion(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='versions')
    user = models.ForeignKey(WebUser, on_delete=models.SET_NULL, null=True)
    content = RichTextField()
    timestamp = models.DateTimeField(default=timezone.now)

HomeApp/forms.py
from django import forms
from .models import Post, Comment
from AccountApp.models import Rating

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'type_of_post']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your post content here...'}),
            'type_of_post': forms.Select(attrs={'class': 'form-control'}),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
                        'content': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Enter your Comment here...'}),

        }

class PostEditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 8}),  # Customize textarea attributes
        }

class RatingForm(forms.ModelForm):
    LANGUAGE_CHOICES = [
        ('English', 'English'),
        ('German', 'German'),
        ('Japanese', 'Japanese'),
    ]

    language = forms.ChoiceField(choices=LANGUAGE_CHOICES, widget=forms.Select(attrs={'class': 'form-select'}))
    stars = forms.DecimalField(widget=forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter stars here'}))

    class Meta:
        model = Rating
        fields = ['language', 'stars']

HomeApp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.shortcuts import render, redirect
from .forms import PostForm, CommentForm, PostEditForm
from .models import Post, PostVersion, OriginalPostContent
from AccountApp.models import Rating, WebUser
from .forms import RatingForm




def HomeView(request):
    return render(request, 'HomeApp/HomePage.html')

@login_required
def CreatePostView(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()

            # Save the original content of the post
            post_content = form.cleaned_data['content']
            OriginalPostContent.objects.create(post=post, content=post_content)

            return redirect('HomeApp:ViewHome')
    else:
        form = PostForm()

    return render(request, 'HomeApp/PostPage.html', {'form': form})


def ViewPostView(request):
    get_posts = Post.objects.all()
    context = {'PostData':get_posts}
    return render(request, 'HomeApp/ViewPostPage.html', context)

@login_required
def ViewPostDetail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    # Get the original post content
    original_version = OriginalPostContent.objects.filter(post=post).first()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.post = post
            comment.save()
            return redirect('HomeApp:ViewPostDetail', post_id=post_id)
    else:
        form = CommentForm()
    comments = post.comments.all()
    context = {'post': post, 'comments': comments, 'form': form, 'original_version': original_version}
    return render(request, 'HomeApp/ViewPostDetail.html', context)

@login_required
def ViewEditPost(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == 'POST':
        form = PostEditForm(request.POST, instance=post)
        if form.is_valid():
            content = form.cleaned_data['content']
            # Save the original post content
            PostVersion.objects.create(post=post, user=request.user, content=post.content)
            # Update the post content
            post.content = content
            post.save()
            return redirect('HomeApp:ViewPostDetail', post_id=post.id)
    else:
        form = PostEditForm(instance=post)

    context = {'post': post, 'form': form}
    return render(request, 'HomeApp/ViewEditPost.html', context)

@login_required
def ViewChangesVersion(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    # Get all versions of the post
    versions = PostVersion.objects.filter(post=post)

    # Get the original post content
    original_version = OriginalPostContent.objects.filter(post=post).first()

    context = {
        'post': post,
        'versions': versions,
        'original_version': original_version,
    }

    return render(request, 'HomeApp/ViewChangeVersion.html', context)

@login_required
def ViewRateUser(request, user_id):
    rated_user = WebUser.objects.get(id=user_id)
    if request.method == 'POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating = form.save(commit=False)
            rating.rater = request.user
            rating.rated_user = rated_user
            rating.save()
            return redirect('HomeApp:ViewPostView')
    else:
        form = RatingForm()
    return render(request, 'HomeApp/ViewRateUser.html', {'form': form})

@login_required
def ViewUserProfile(request, user_id):
    profile = get_object_or_404(WebUser, id=user_id)
    context = {'profile': profile}
    return render(request, 'HomeApp/ViewUserProfile.html', context)


def ViewDeletePost(request, post_id):
    if request.method == "POST":
        get_post = get_object_or_404(Post, pk=post_id)
        get_post.delete()
        return redirect("HomeApp:ViewPostView")

    return render(request, 'HomeApp/ViewDeletePost.html')

HomeApp/templates/HomeApp/HomePage.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<main class="container">
    <div class="row mt-5 align-items-center">
        <div class="col-md-6">
            <h2>Welcome to Learn Language</h2>
            <p class="lead">Learn Language is a platform dedicated to helping you master new languages.</p>
            <p>Whether you're a beginner or an advanced learner, our comprehensive resources and interactive tools will
                guide you through your language learning journey.</p>
            <p>Start exploring now and unlock your potential to speak, read, and write in a new language!</p>
        </div>
        <div class="col-md-6">
            <img src="{% static 'assets/images/language.jpeg' %}" class="img-fluid rounded" alt="Language Image">
        </div>
    </div>
</main>
{% endblock content %}

HomeApp/templates/HomeApp/PostPage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3 text-center">
                    <label for="cke_id_content" class="form-label"><strong>Post Content</strong></label>
                    {{ form.media }}
                    {{ form.content }}
                </div>
                <div class="mb-3 text-center">
                    <label for="id_type_of_post" class="form-label"><strong>Type of Post</strong></label>
                    {{ form.type_of_post }}
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

HomeApp/templates/HomeApp/ViewChangeVersion.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">Original Post Content</h1>
            <p class="card-text">{{ original_version.content|safe }}</p>
            <hr>
            <h2 class="card-title">Post Owner</h2>
            <p class="card-text">{{ post.user.username }}</p>
            <hr>
            <h2 class="card-title">Changes:</h2>
            {% if versions %}
            {% for version in versions %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">Changes by: {{ version.user.username }}</h5>
                    <p class="card-text">{{ version.content|safe }}</p>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <p>No changes yet.</p>
            {% endif %}
            <!-- Go Back Button -->
            <a href="{% url 'HomeApp:ViewPostDetail' post.id %}" class="btn btn-secondary">Go Back</a>
        </div>
    </div>
</div>
{% endblock content %}

HomeApp/templates/HomeApp/ViewDeletePost.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body text-center">
            <h1 class="card-title mb-4">Are you Sure?</h1>

            <form method="post" class="mb-3">
                {% csrf_token %}

                <div class="d-flex justify-content-center mb-3">
                    <button type="submit" class="btn btn-danger mr-2">Delete</button>
                    <a href="{% url 'HomeApp:ViewPostView' %}" class="btn btn-secondary">Go Back</a>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock content %}

HomeApp/templates/HomeApp/ViewEditPost.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3 text-center"> <!-- Center align the label -->

                    {{ form.media }}
                    {{ form.content }}
                </div>
                <div class="text-center"> <!-- Center align the button -->
                    <button type="submit" class="btn btn-primary">Save Changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

HomeApp/templates/HomeApp/ViewPostDetail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-4">
    <div class="card">
        <div class="card-body">
            <h1 class="card-title">{{ post }}</h1>
            <p class="card-text">{{ original_version.content|safe }}</p>
            <!-- Edit option -->
            <div class="d-flex justify-content-center mb-3"> <!-- Centering the button -->
                {% if user.is_authenticated %}
                <a href="{% url 'HomeApp:ViewEditPost' post.id %}" class="btn btn-primary">Fix Content</a>

                &nbsp;

                <a href="{% url 'HomeApp:ViewChangesVersion' post.id %}" class="btn btn-primary">View Changes</a>
                {% endif %}

            </div>
            <hr>
            <h2 class="card-title">Comments:</h2>
            {% for comment in post.comments.all %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">Comment by: {{ comment.user.username }}</h5>
                    <p class="card-text">{{ comment.content|safe }}</p>
                </div>
            </div>
            {% empty %}
            <p>No comments yet.</p>
            {% endfor %}
            <!-- Form for adding a comment -->
            <h3>Add a comment:</h3>
            <form method="post" action="{% url 'HomeApp:ViewPostDetail' post.id %}" class="mb-3">
                {% csrf_token %}
                <div class="form-group mb-3 text-center"> <!-- Added mb-3 class here -->
                    {{ form.media }}
                    {{ form.content }}
                </div>
                <div class="d-flex justify-content-center"> <!-- Centering the button -->
                    <button type="submit" class="btn btn-primary">Comment</button>
                </div>
            </form>

        </div>
    </div>
</div>
{% endblock content %}

HomeApp/templates/HomeApp/ViewPostPage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<table class="container table">
    <thead>
        <tr>
            <th scope="col">Sr No</th>
            <th scope="col">Post</th>
            <th scope="col">Author</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
        {% for data in PostData %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td><a href="{% url 'HomeApp:ViewPostDetail' data.id %}">{{ data.content|safe }}</a></td>
            <td>{{ data.user.username }}</td>
            <td>
                {% if request.user.is_superuser %}
                <!-- Admin-specific actions -->
                <a href="{% url 'HomeApp:ViewEditPost' data.id %}">Edit</a>
                <a href="{% url 'HomeApp:ViewRateUser' data.user.id %}">Rate Author</a>
                <a href="{% url 'HomeApp:ViewProfile' data.user.id %}">View Profile</a>
                <a href="{% url 'HomeApp:ViewDeletePost' data.id %}">Delete Post</a>
            {% else %}
                <!-- Non-admin actions -->
                <a href="{% url 'HomeApp:ViewEditPost' data.id %}">Edit</a>
                <a href="{% url 'HomeApp:ViewRateUser' data.user.id %}">Rate Author</a>
                <a href="{% url 'HomeApp:ViewProfile' data.user.id %}">View Profile</a>
            {% endif %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

HomeApp/templates/HomeApp/ViewRateUser.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Rate User</h5>
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_language" class="form-label">Language</label>
                            {{ form.language }}
                        </div>
                        <div class="mb-3">
                            <label for="id_stars" class="form-label">Stars</label>
                            {{ form.stars }}
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

HomeApp/templates/HomeApp/ViewUserProfile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>{{ profile.username }}</h1>
    <div class="row">
        <div class="col-md-6">
            <p><strong>Birthdate:</strong> {{ profile.birth_year }}/{{ profile.birth_month }}/{{ profile.birth_day }}
            </p>
        </div>
        <div class="col-md-6">
            <p><strong>Gender:</strong> {{ profile.gender }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <p><strong>Full Name:</strong> {{ profile.first_name }} {{ profile.last_name }}</p>
        </div>
        <div class="col-md-6">
            <p><strong>Email:</strong> {{ profile.email }}</p>
        </div>
    </div>


    <h2 class="mt-4">Ratings</h2>
    <div class="row">
        {% if profile.ratings_received.all %}
        {% for rating in profile.ratings_received.all %}
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">{{ rating.language }}</h5>
                    <p class="card-text">Stars: {{ rating.stars }}</p>
                    <p class="card-text">Rated by: {{ rating.rater.username }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col">
            <div class="alert alert-info" role="alert">
                This user hasn't been rated yet.
            </div>
            <a href="{% url 'HomeApp:ViewRateUser' profile.id %}" class="btn btn-primary">Rate {{profile.username}}</a>
        </div>
        {% endif %}
    </div>

</div>

</div>
{% endblock %}