AccountApp/urls.py
from django.urls import path
from . import views

app_name = 'AccountApp'

urlpatterns = [
    path('signup/', views.UserSignUpView.as_view(), name="ViewSignup"),
    path('login/', views.UserLoginView.as_view(), name="ViewLogin"),
    path('logout/', views.UserLogoutView.as_view(), name="ViewLogout"),
    path('search_user/', views.ViewFilterUser, name="ViewFilterUser"),

        # Rest API
    path('api/users/', views.UserSearchAPIView.as_view(), name="api_user_search"),
]

HomeApp/urls.py
from django.urls import path, include
from . import views

app_name = 'HomeApp'


urlpatterns = [
    path('', views.HomeView, name="ViewHome"),
    path('create_post/', views.CreatePostView, name="ViewCreatePost"),
    path('view_post/', views.ViewPostView, name="ViewPostView"),
    path('reply_post/<int:post_id>/', views.ViewPostDetail, name="ViewPostDetail"),
    path('edit_post/<int:post_id>/', views.ViewEditPost, name="ViewEditPost"),
    path('view_changes/<int:post_id>/', views.ViewChangesVersion, name="ViewChangesVersion"),
    path('rate_user/<int:user_id>/', views.ViewRateUser, name="ViewRateUser"),
    path('view_profile/<int:user_id>/', views.ViewUserProfile, name="ViewProfile"),
    path('delete_post/<int:post_id>', views.ViewDeletePost, name="ViewDeletePost")



]

sprache/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("HomeApp.urls")),
    path('account/', include("AccountApp.urls")),
]

templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">

<head>
    {% load static %}

    <script src="{% static 'assets/js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Learn English</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/sign-in/">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'assets/dist/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Custom styles for this template -->
    <link href="{% static 'assets/custom_css/signup_custom.css' %}" rel="stylesheet">
    <link href="{% static 'assets/custom_css/bootstrap_custom_css.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'assets/custom_css/navbar.css' %}" rel="stylesheet">
</head>

<body>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="check2" viewBox="0 0 16 16">
            <path
                d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
        </symbol>
        <symbol id="circle-half" viewBox="0 0 16 16">
            <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
        </symbol>
        <symbol id="moon-stars-fill" viewBox="0 0 16 16">
            <path
                d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
            <path
                d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
        </symbol>
        <symbol id="sun-fill" viewBox="0 0 16 16">
            <path
                d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
        </symbol>
    </svg>

    <div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
        <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
            aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
            <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
                <use href="#circle-half"></use>
            </svg>
            <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
        </button>
        <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                    <svg class="bi me-2 opacity-50" width="1em" height="1em">
                        <use href="#sun-fill"></use>
                    </svg>
                    Light
                    <svg class="bi ms-auto d-none" width="1em" height="1em">
                        <use href="#check2"></use>
                    </svg>
                </button>
            </li>
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                    <svg class="bi me-2 opacity-50" width="1em" height="1em">
                        <use href="#moon-stars-fill"></use>
                    </svg>
                    Dark
                    <svg class="bi ms-auto d-none" width="1em" height="1em">
                        <use href="#check2"></use>
                    </svg>
                </button>
            </li>
            <li>
                <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                    <svg class="bi me-2 opacity-50" width="1em" height="1em">
                        <use href="#circle-half"></use>
                    </svg>
                    Auto
                    <svg class="bi ms-auto d-none" width="1em" height="1em">
                        <use href="#check2"></use>
                    </svg>
                </button>
            </li>
        </ul>
    </div>


    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'HomeApp:ViewHome' %}">DNG Learn Language</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'HomeApp:ViewHome' %}">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Post
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="{% url 'HomeApp:ViewCreatePost' %}">Create Post</a></li>
                            <li><a class="dropdown-item" href="{% url 'HomeApp:ViewPostView' %}">View Post</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="{% url 'AccountApp:ViewFilterUser' %}">Search User</a>
                        </li>
                    <!-- <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
                    </li> -->


                </ul>
                <div class="d-flex">

                    {% if user.is_authenticated %}
                    <div class="d-flex">
                        <a href="{% url 'AccountApp:ViewLogout' %}" class="btn btn-outline-success">Logout</a>
                    </div>
                    {% else %}
                    <div class="d-flex">
                        <a href="{% url 'AccountApp:ViewLogin' %}" class="btn btn-outline-success">Login</a>
                    </div>

                    {% endif %}

                </div>

            </div>
        </div>
    </nav>

    <main class="container">
        {% block content %}

        {% endblock content %}
    </main>

    <script src="{% static 'assets/dist/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>